language: node_js
node_js:
  - "10.15.0"
cache:
  directories:
    - node_modules
    - /home/travis/.cache/Cypress
script:
  - npm install
  - npm install coveralls
  - npm run build
  - npm test -- --coverage


after_success:
  - coveralls < coverage/lcov.info
